import { baseApi } from "../base";
import { LinkExternalAccountRequest, LinkExternalAccountResponse } from "./types";

/**
 * This method is used to link an external account (e.g. Plaid).
 * @link https://api.norcapsecurities.com/admin_v3/documentation?mid=MQ==
 * @param {string} clientID - Transact API Client ID
 * @param {string} developerAPIKey - Transact API Developer Key
 * @param {string} accountId - Account ID generated by the API
 */
export default async function ({
  clientID,
  developerAPIKey,
  accountId
}: LinkExternalAccountRequest): Promise<LinkExternalAccountResponse> {
  try {
    const payload: LinkExternalAccountRequest = {
      clientID,
      developerAPIKey,
      accountId
    };
    return await baseApi("POST", "linkExternalAccount", payload);
  } catch (error) {
    throw new Error(error.message);
  }
}
