import { baseApi } from "../base";
import { SendSubscriptionDocumentRequest, SendSubscriptionDocumentResponse } from "./types";

/**
 * This method is used to send the subscription documents for the primary party(createParty) that is linked with the account(createAccount) to sign.
 * @link https://api-sandboxdash.norcapsecurities.com/admin_v3/documentation?mid=MjE2
 * @param {string} clientID Transact API Client ID
 * @param {string} developerAPIKey Transact API Developer Key
 * @param {string} accountId Account ID that is generated by the API once an account is created(createAccount)
 * @param {string} offeringId Offering ID that is generated by the API once an offering is created(createOffering)
 * @param {string} tradeId Trade ID that is generated by the API once an trade is created(createTrade).
 * @returns {string} statusCode - API Status Code
 * @returns {string} statusDesc - API Status Description
 * @returns {array} document_details - Document details of the matched Party ( documentKey, esignStatus, partyId)
 */
export default async function ({
  clientID,
  developerAPIKey,
  accountId,
  offeringId,
  tradeId
}: SendSubscriptionDocumentRequest): Promise<SendSubscriptionDocumentResponse> {
  try {
    const payload: SendSubscriptionDocumentRequest = {
      clientID,
      developerAPIKey,
      accountId,
      offeringId,
      tradeId
    };
    return await baseApi("POST", "sendSubscriptionDocument", payload);
  } catch (error) {
    throw new Error(error.message);
  }
}
